# Generated by Django 4.1.1 on 2022-09-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdetails',
            old_name='full_names',
            new_name='fullnames',
        ),
    ]
